name: Cybertill Tech Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Install dependencies
      - name: Run Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      # Save Composer Artifacts
      - uses: actions/upload-artifact@master
        with:
          name: composer-artifact
          path: vendor

  configuration:
    name: Prepare Cybertill Application
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1

      - uses: actions/download-artifact@master
        with:
          name: composer-artifact
          path: vendor

      # Configure Application
      - name: Prepare The Application
        run: |
          chmod 777 -R ./Application/storage/
          chmod 777 -R ./Domain/database/
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php -r "file_exists('./Domain/database/cybertill.sqlite') || copy('./Domain/database/cybertill.sqlite.example', './Domain/database/cybertill.sqlite');"
          php artisan cache:clear
          php artisan migrate:refresh
