name: Cybertill Tech Test

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Build the application files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Install dependencies
      - name: Run Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      # Configure Application
      - name: Prepare The Application
        run: |
          chmod 777 -R ./Application/storage/*
          chmod 777 -R ./Domain/database/
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php -r "file_exists('./Domain/database/cybertill.sqlite') || copy('./Domain/database/cybertill.sqlite.example', './Domain/database/cybertill.sqlite');"
          php artisan cache:clear
          php artisan migrate:refresh
      # Unit Test
      - name: Run PHPUnit Test
        run: vendor/bin/phpunit
